Completed Feature Set
rsundar/covid19-country-dashboard pull request #1
Opened 2021-09-23 17:40 UTC by rsundar

## FEATURES ADDED

- Created an app using Create React App,
- Got covid19 data from the Narrativa API,
- Built a Hompage component comprising  a list of country names and total case count,
- Built a Country specific detail page comprising region wise breakdown of cases,
- Created unique routes for each country.

2021-09-23 20:08 UTC, oloomoses requested changes
Hi @rsundar, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add mock tests for the API and the functions you have created as per the project requirements.

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 20:08 UTC, oloomoses commented on src/Components/home.jsx
> +};
- [x] Kindly move this filter into its own component and then you can import it into the home component. The filter should be a component on its own and should be stateless.

2021-09-23 20:08 UTC, oloomoses commented on src/App.js
>        </header>
- [x] Your design does not match the given one. Kindly add all the icons in the navigation bar even if they are not functional.

2021-09-23 20:08 UTC, oloomoses commented on src/redux/configStore.js
> +);
- [x] Please do not log redux data on the browser console as it may cause site security issues. Kindly clear the logged data and errors displayed on the browser console.

2021-09-24 14:41 UTC, rsundar commented on src/Components/home.jsx
> +};
Moved to FilterInput.jsx and imported as needed

2021-09-27 15:22 UTC, rsundar commented on src/App.js
>        </header>
Done

2021-09-27 15:24 UTC, rsundar commented on src/redux/configStore.js
> +);
Done

2021-09-27 15:25 UTC, rsundar commented
## CHANGES MADE

- Moved the Api calls into a saperate utils folder for better maintainability,
- Moved the filter into a saperate component and imported as needed,
- Add the required functional icons on the nav bar,
- Added tests for the Api calls

2021-09-28 17:56 UTC, merged